### ISSUE TITLE
Dafny VSCode Plugin Uninstaller Hangs

### ISSUE THREAD

**Issue by kevinsullivan** [DafnyVSCode/Dafny-VSCode#16]
Trying to narrow down the causes of the "Server Crashed 5 Times" bug (see other issue) I tried to uninstall the plug-in. What I got a was a hung uninstaller. Killing and restarting VSCode showed that the plugin is still installed. This is clearly a bug.

**Comment by fabianhauser** [comment]
Thanks for reporting this issue. Could you provide some more details? I was not able to reproduce the error on my test setups. Thanks!

**Comment by fabianhauser** [comment]
Closing, as the error could not be reproduced and no further information is available.
