### ISSUE TITLE
Extension deletes files irrecoverably

### ISSUE THREAD

**Issue by kevinsullivan** [DafnyVSCode/Dafny-VSCode#20]
A student reported to me about a week ago that he had created a file of class notes and that it simply disappeared on him. I did't disbelieve him, but I also couldn't confirm that it was due to a fault in the plug-in. Now I can.

I just saw it myself. After working for several hours in the IDE (unfortunately without a commit), I got a "server failed 5 times and won't restart" error, which I've seen many times, but then immediately after that I got a "file not found, do you want to create it?" error. The file had been opened in a tab in the IDE. Now it was gone.

There's no question but that the IDE deleted the file, and it seems unrecoverable, as the file is not in my trashcan (on OSX). The file that was deleted was not the file I was working on at the moment the errors occurred.

This just cost me several hours of work.  Clearly a bug like this is a "must fix" before this plug-in can be considered viable for broader use.

**Comment by fabianhauser** [comment]
As I really do not see any way in which the extension could delete a file,
and there was no feedback since January, I am closing this issue for now.

Feel free to reopen if you have more details or see it happening again!
