### ISSUE TITLE
CodeLens functionality annotates words within comments

### ISSUE THREAD

**Issue by kevinsullivan** [DafnyVSCode/Dafny-VSCode#22]
And it shouldn't.

**Comment by pipeaesac** [comment]
Hey @kevinsullivan , can you provide a small example for me to verify? I would like to look into this issue.

**Comment by fabianhauser** [comment]
Hi @kevinsullivan 

I was not able to reproduce the error. If the problem please exist, feel free to reopen this issue. Thanks!

Fabian
