### ISSUE TITLE
Counterexamples not shown

### ISSUE THREAD

**Issue by fmehta** [DafnyVSCode/Dafny-VSCode#23]
The `dafny.showCounterExample` command seems to have no effect. This has been noticed after updating to version 0.11.1 of the plugin and version 2.1.1 of the Dafny server.

OS: MacOS 10.13.4

**Comment by pipeaesac** [comment]
I can confirm the issue on MacOS 10.14 Beta, plugin version 0.11.1. and Dafny server version 3.5.0 (?). Labelling it as a bug.

**Comment by pipeaesac** [comment]
While debugging the server on the counterModel request, I was able to get a counter example twice. This happened only by accident and the only similarity between the two successful requests was the huge delay introduced in the server by a breakpoint. It seems that the Dafny binary takes a very long time to calculate the counter example. The example code I used was the one from the README:

```
method Abs(x: Int)
    returns (y: int)
ensures y >= 0 {
    return x;
}
```

**Comment by kevinsullivan** [comment]
I read somewhere that showing of counterexamples has been disabled due to
performance concerns, but can be enabled by the setting of a configuration
parameter. Sorry, I can't provide more information now, as I'm somewhere
with very poor internet connectivity.

**Comment by fmehta** [comment]
Dear Kevin,
You are right. Counterexamples take some time and processing power to generate. Therefore we decided that we should be able to toggle them with VS Code using the function keys. This is intended behaviour and worked well. This was instantaneous for the `Abs` example that @pipeaesac mentioned earlier in the thread.

Currently (i.e. after the update to the new Dafny version and the new Plugin version), it seems that the counterexamples are no more shown (or maybe just take too long). For me, the counterexample for the `Abs` example is not shown.

I may be wrong, but this may have something to do with an update to Dafny itself, since the code for processing counterexamples in the plugin does not seem to have changed. 
@RustanLeino : Do you know of any changes in Dafny itself that could cause something like this?

Best regards,
Farhad

**Comment by ruimaranhao** [comment]
Is there any update on this? Is there any way to force the counter example to be shown?

**Comment by fmehta** [comment]
Hi ruimaranhao,
Sorry, there is currently nothing further on this issue that I can report. I have added the "help wanted" tag to it, so feel free to look into it if you have the time. Directions for contributing are on the GitHub pages.
Best regards,
Farhad

**Comment by fabianhauser** [comment]
I added a workaround to the upstream bug that ships with the newest release (`v0.14.2`).
Could you try if that works for you @ruimaranhao?
