### ISSUE TITLE
Lots of duplication in Readme and client/Readme

### ISSUE THREAD

**Issue by misto** [DafnyVSCode/Dafny-VSCode#4]
There's a lot of duplication in the two readmes. It seems that the client/Readme is used for the marketplace entry. Could we remove the duplicated parts from the root Readme and instead focus more on  development/release/contributions there? What do @markusschaden and @ValisStigma think?

**Comment by pipeaesac** [comment]
I already removed a lot of the duplicated documentation. Will add a more fitting description for the root repository soon.

**Comment by pipeaesac** [comment]
Duplication in READMEs and no longer needed repositories removed. Repositories renamed.
