### ISSUE TITLE
Dafny-VSCode doesn't connect to language server under Linux

### ISSUE THREAD

**Issue by csgordon** [DafnyVSCode/Dafny-VSCode#51]
I just tried the extension on Windows yesterday, and it installed a Dafny distribution and was up and running as soon as it finished downloading --- brilliant!

Under Linux today, I'm not having such luck.  I installed the extension itself without issue, and was prompted to install Dafny upon opening a dfy file.  I clicked yes, it seemed to download as expected... then asked me again if I wanted to install Dafny.  (I can click Yes, it will download again, then ask again; I've repeated this process several times now since I first encountered the general issues below just to see if it would fix things, to no avail.)

If I try to compile a file, I get:
```
Can't compile: The Server was not ready to handle the client request
```
Waiting 10 minutes doesn't affect anything, so I assume this is not some weird slow-startup issue.

I've restarted Visual Studio Code, and attempted to restart the language server through the extension, several times each without success.

After installation it does set the Dafny Base Path to ```/home/csgordon/.vscode/extensions/correctnesslab.dafny-vscode-0.17.1/dafny/dafny```, which appears to contain the expected contents of a Dafny distribution.  For good measure I've tried with and without manually setting the path to mono (version 4.6.2), which seems to make no difference.

It doesn't appear that the language server itself is actually running:
```
/home/csgordon> ps aux | grep -i dafny
csgordon 23276  0.0  0.2 566804 68312 ?        Sl   09:33   0:00 /usr/share/code/code /home/csgordon/.vscode/extensions/correctnesslab.dafny-vscode-0.17.1/node_modules/vscode-languageclient/lib/utils/electronForkStart /home/csgordon/.vscode/extensions/correctnesslab.dafny-vscode-0.17.1/server/server.js --node-ipc --clientProcessId=23240
csgordon 24612  0.0  0.0  14428  1068 pts/1    S+   09:41   0:00 /bin/grep -i dafny
```
if I'm correctly interpreting process 23276 above as the extension itself.

The output in the Visual Studio Code UI for Dafny Language Server is just a periodically-updated string of:
```
[Error - 9:34:01 AM] Request textDocument/codeLens failed.
  Message: Request textDocument/codeLens failed unexpectedly without providing any details.
  Code: -32603 
[Error - 9:38:41 AM] Request textDocument/codeLens failed.
  Message: Request textDocument/codeLens failed unexpectedly without providing any details.
  Code: -32603 
[Error - 9:39:55 AM] Request textDocument/codeLens failed.
  Message: Request textDocument/codeLens failed unexpectedly without providing any details.
  Code: -32603 
[Error - 9:39:56 AM] Request textDocument/codeLens failed.
  Message: Request textDocument/codeLens failed unexpectedly without providing any details.
  Code: -32603 
[Error - 9:39:59 AM] Request textDocument/codeLens failed.
  Message: Request textDocument/codeLens failed unexpectedly without providing any details.
  Code: -32603 
[Error - 9:40:01 AM] Request textDocument/codeLens failed.
  Message: Request textDocument/codeLens failed unexpectedly without providing any details.
  Code: -32603 
[Error - 9:40:02 AM] Request textDocument/codeLens failed.
  Message: Request textDocument/codeLens failed unexpectedly without providing any details.
  Code: -32603 
[Error - 9:40:03 AM] Request textDocument/codeLens failed.
  Message: Request textDocument/codeLens failed unexpectedly without providing any details.
  Code: -32603 
[Error - 9:40:06 AM] Request textDocument/codeLens failed.
  Message: Request textDocument/codeLens failed unexpectedly without providing any details.
  Code: -32603 
[Error - 9:40:32 AM] Request textDocument/codeLens failed.
  Message: Request textDocument/codeLens failed unexpectedly without providing any details.
  Code: -32603 
[Error - 9:40:33 AM] Request textDocument/codeLens failed.
  Message: Request textDocument/codeLens failed unexpectedly without providing any details.
  Code: -32603 
```
I'm not aware of any other places to look for relevant logs, but I'm happy to provide them if there's somewhere I should look.

I'm running Linux Mint (an Ubuntu derivative) 19.1, with Visual Studio Code 1.36.1, and Mono 4.6.2 (technically an Ubuntu tweak on a Debian tweak, version 4.6.2.7+dfsg-1ubuntu1 in the Ubuntu derivative repositories).

The configuration for my machine is pretty much a stock install, with the exception of the default shell being PowerShell rather than bash, so if the default shell matters that could be an issue, though I haven't observed problems with other vscode extensions that launch external programs (e.g., LaTeX extensions).  Bash is still available on my system, though, so the ```dafny``` and ```dafny-server``` scripts that start with ```#!/usr/bin/env bash``` should still run fine once invoked.

**Comment by fabianhauser** [comment]
It seems that the Plugin is not able to start the Dafny Language Server on your system. As far as I can tell, this should be independent of your default shell (where/how exactly do you have that configured?).

To make sure this is not a Dafny issue, could you try to run the Dafny Language Server manually?

```bash
cd /home/csgordon/.vscode/extensions/correctnesslab.dafny-vscode-0.17.1/dafny/dafny
./dafny-server
```

and then insert a verification request (be careful to copy paste each line separately and to not include extra characters):
```
counterExample
eyJhcmdzIjpbXSwiZmlsZW5hbWUiOiJjOlxcREVWXFxEYWZueVxcYWJzLmRmeSIsInNvdXJjZSI6Im1ldGhvZCBBYnMoeDogaW50KSBcclxuICAgIHJldHVybnMgKHk6IGludClcclxuZW5zdXJlcyB5ID49IDAge1xyXG4gICAgcmV0dXJuIHg7XHJcbn0iLCJzb3VyY2VJc0ZpbGUiOmZhbHNlfQ==
[[DAFNY-CLIENT: EOM]]
```

**Comment by csgordon** [comment]
```
PS /home/csgordon/.vscode/extensions/correctnesslab.dafny-vscode-0.17.1/dafny/dafny> ./dafny-server

Unhandled Exception:
System.MissingFieldException: Field 'Microsoft.Boogie.ExecutionEngine.printer' not found.
  at Microsoft.Dafny.Server.Main (System.String[] args) [0x00000] in <2583557f32694705aeba9882deecf445>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.MissingFieldException: Field 'Microsoft.Boogie.ExecutionEngine.printer' not found.
  at Microsoft.Dafny.Server.Main (System.String[] args) [0x00000] in <2583557f32694705aeba9882deecf445>:0 
PS /home/csgordon/.vscode/extensions/correctnesslab.dafny-vscode-0.17.1/dafny/dafny>
```
I get the same error running via bash:
```
[csgordon:~/.vscode/extensions/correctnesslab.dafny-vscode-0.17.1/dafny/dafny]$ ./dafny-server 

Unhandled Exception:
System.MissingFieldException: Field 'Microsoft.Boogie.ExecutionEngine.printer' not found.
  at Microsoft.Dafny.Server.Main (System.String[] args) [0x00000] in <2583557f32694705aeba9882deecf445>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.MissingFieldException: Field 'Microsoft.Boogie.ExecutionEngine.printer' not found.
  at Microsoft.Dafny.Server.Main (System.String[] args) [0x00000] in <2583557f32694705aeba9882deecf445>:0 
[csgordon:~/.vscode/extensions/correctnesslab.dafny-vscode-0.17.1/dafny/dafny]$
```

I've not used Mono much myself (mostly .NET Framework on Windows and .NET Core elsewhere), but I installed Mono the typical way for a Debian derivative (apt-get).

**Comment by fabianhauser** [comment]
I'd suggest you try installing a new upstream Mono version from https://www.mono-project.com/download/stable/#download-lin-ubuntu, as many distributions ship rather old mono versions.

The error is coming from the Dafny compiler itself, so you would have to open an issue at the [Dafny Project](https://github.com/dafny-lang/dafny/) if the problem persists. They might be able to help you further 🙂

**Comment by csgordon** [comment]
Thanks!
