### ISSUE TITLE
Error: starting dafny client failed

### ISSUE THREAD

**Issue by johnwickerson** [DafnyVSCode/Dafny-VSCode#52]
I had Dafny working nicely in VS Code (on Mac OS X). Today, VS Code seems to have installed itself an upgrade, and now Dafny is no longer working. Specifically, I get the following error message:

> [Error - 7:13:46 AM] Starting client failed
> Error: spawn /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper ENOENT
> 	at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
>	at onErrorNT (internal/child_process.js:407:16)
>	at process._tickCallback (internal/process/next_tick.js:63:19)

I tried running `./dafny_server` from the command line, as suggested [here](https://github.com/DafnyVSCode/Dafny-VSCode/issues/51#issuecomment-512726671) and it seemed to be working fine.

Could somebody advise on next steps? Thanks!

> Version: 1.39.0
> Commit: 9df03c6d6ce97c6645c5846f6dfa2a6a7d276515
> Date: 2019-10-09T06:57:43.593Z
> Electron: 4.2.10
> Chrome: 69.0.3497.128
> Node.js: 10.11.0
> V8: 6.9.427.31-electron.0
> OS: Darwin x64 18.7.0

**Comment by fabianhauser** [comment]
I don't think that this is a Dafny VSCode issue but rather a VSCode bug. If you search for this error, you find many issues like [this one](https://github.com/redhat-developer/vscode-yaml/issues/117).
The solution there was reinstalling VSCode and clearing the VSCode settings, could you try that?

**Comment by johnwickerson** [comment]
Thanks! This worked. I followed [this advice](https://medium.com/@jimkang/complete-uninstall-remove-vscode-mac-5e48bef3bdec) for how to uninstall VSCode and clear all its settings.
